# Generated by Django 5.0.7 on 2024-08-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_category_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='user',
        ),
    ]
