# Generated by Django 4.2.13 on 2025-04-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
