# Generated by Django 4.2.13 on 2025-04-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_customer_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordertime',
            new_name='order_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='main.customer'),
        ),
    ]
