# Generated by Django 4.2.13 on 2025-04-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_file',
            field=models.FileField(null=True, upload_to='product_files/'),
        ),
    ]
