# Generated by Django 4.2.13 on 2025-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_product_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downloads',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
