# Generated by Django 4.2.13 on 2025-04-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_product_usd_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='usd_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
