# Generated by Django 4.2.13 on 2025-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='usd_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
