# Generated by Django 4.2.13 on 2025-05-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_vendor_mobile_vendor_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_status',
            field=models.BooleanField(default=False),
        ),
    ]
