# Generated by Django 4.2.13 on 2025-05-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_product_published_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrating',
            options={'verbose_name_plural': 'Product Rating'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='category_imgs/'),
        ),
    ]
