# Generated by Django 4.2.13 on 2025-08-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_productrating_options_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trans_ref',
            field=models.TextField(blank=True, null=True),
        ),
    ]
